# Generated by Django 4.2.3 on 2023-08-01 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0001_initial"),
        ("drf_api_key", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="expiry_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Once API key expires, clients cannot use it anymore.",
                null=True,
                verbose_name="expiry date",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="hashed_key",
            field=models.CharField(
                editable=False, max_length=150, verbose_name="hashed key"
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=150,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="name",
            field=models.CharField(
                default=None,
                help_text="A free-form unique name for the API key.",
                max_length=50,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="prefix",
            field=models.CharField(
                editable=False, max_length=8, unique=True, verbose_name="prefix"
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="revoked",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="If the API key is revoked, clients cannot use it anymore.",
                verbose_name="revoked",
            ),
        ),
        migrations.CreateModel(
            name="HeroAPIKey",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=150,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        editable=False, max_length=8, unique=True, verbose_name="prefix"
                    ),
                ),
                (
                    "hashed_key",
                    models.CharField(
                        editable=False, max_length=150, verbose_name="hashed key"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=None,
                        help_text="A free-form unique name for the API key.",
                        max_length=50,
                        verbose_name="name",
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="If the API key is revoked, clients cannot use it anymore.",
                        verbose_name="revoked",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Once API key expires, clients cannot use it anymore.",
                        null=True,
                        verbose_name="expiry date",
                    ),
                ),
                (
                    "hero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="heroes.hero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero API key",
                "verbose_name_plural": "Hero API keys",
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
    ]
