# Generated by Django 3.2.16 on 2023-01-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('retired', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'heroes',
            },
        ),
    ]
